# from agroEcoData import ExtractProjectAgroEcoData, ExtractAllAgroEcoData
# from contextData import subsetScoresByVariables, ScoresForAllAttributes, projectContextScores, ContextScoresAllProjectsList, ContextScoresAllProjects
# from pairwiseData import pairWiseSelectionsProjectGender, pairWiseSelectionsProject, pairWiseSelectionsAllProjects, pairWiseSummaryScores, pairWiseSelectionSummaryAllProjects
# from participatoryMatricData import participatoryMatrixScoresProject, participatoryMatrixAllProjects
# from legumeData import extractLegumeResults, extractAllLegumeData

#import agroEcoData
import pandas as pd